### ISSUE TITLE
IfICmpEqInst.execute Integer equal issue

### ISSUE THREAD

**Issue by raoshaoquan** [guxingke/mini-jvm#15]
`public class IfICmpEqInst implements Instruction {
  public final int offset;

  public IfICmpEqInst(int offset) {
    this.offset = offset;
  }

  @Override
  public int offset() {
    return 3;
  }

  @Override
  public void execute(Frame frame) {
    Integer val2= frame.popInt();
    Integer val1= frame.popInt();
    **### _if (val1 == val2) {_**    //Objects.equals(val1, val2)
      frame.nextPc = frame.thread.getPc() + offset;
    }
  }
}
`

**Comment by guxingke** [comment]
yes, you are right at if valx type is reference , but in this case, the valx always int. not a Integer ref .

**Comment by raoshaoquan** [comment]
I see

**Comment by guxingke** [comment]
sorry , you are right, i meet a corner case . 😂
