### ISSUE TITLE
基类的 clinit 被执行多次 

### ISSUE THREAD

**Issue by 970655147** [guxingke/mini-jvm#28]
master:mini-jvm jerry$ java -jar jvm-core/target/mini-jvm.jar -jar jvm-core/target/mini-jvm.jar -cp . HelloWorld
HelloWorldSuper <clinit>
HelloWorldSuper <clinit>
hello world

HelloWorld.java 
public class HelloWorld extends HelloWorldSuper {
//    static {
//        System.out.println("<clinit>");
//    }
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}

HelloWorldSuper.java
public class HelloWorldSuper {
    static {
        System.out.println("HelloWorldSuper <clinit>");
    }
}

**Comment by guxingke** [comment]
多谢， 经验证，问题缺失存在， 我排查一下。

**Comment by guxingke** [comment]
已修复 

https://github.com/guxingke/mini-jvm/pull/32
